# This docker-compose file starts an entire wasmCloud ecosystem, including:
#   a NATS server
#   a local OCI registry
#   grafana + prometheus + tempo for metrics and tracing
#   a wasmCloud host
#   a WADM server for managing applications

version: "3"
services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "4223:4223"
      - "6222:6222"
      - "8222:8222"
    command:
      - "-c=/etc/nats/nats-server.conf"
      - "-js"
    volumes:
      - ./nats.websocket.conf:/etc/nats/nats-server.conf
    
  registry:
    image: registry:2.8
    ports:
      - "5000:5000"

  grafana:
    image: grafana/grafana:10.0.10
    ports:
      - 5050:3000
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - prometheus
      - tempo
      - loki

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.93.0
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - prometheus
      - tempo
      - loki

  prometheus:
    image: prom/prometheus:v2.49.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml

  loki:
    image: grafana/loki:2.9.4
    command:
      - '-config.file=/etc/loki/config.yaml'
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    ports:
      - 3100:3100
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.3.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - 4318 # This port is used for sending traces from otel-collector to tempo
      - 7999:7999 # tempo

  wasmcloud:
    depends_on:
      - "nats"
      - "otelcol"
      - "tempo"
    image: johannhartmann/wasmcloud:latest
    command:
      - "wasmcloud"
      - "--override-observability-endpoint=http://otelcol:4318"
    volumes:
      - /data:/data
    environment:
      - RUST_LOG=debug,hyper=info,async_nats=info,oci_distribution=info,cranelift_codegen=warn
      - WASMCLOUD_LOG_LEVEL=debug
      - WASMCLOUD_RPC_HOST=nats
      - WASMCLOUD_CTL_HOST=nats
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - WASMCLOUD_ALLOW_FILE_LOAD=true
      - WASMCLOUD_OCI_ALLOWED_INSECURE=registry:5000
      - WASMCLOUD_OBSERVABILITY_ENABLED=true
    ports:
      - "8000-8100:8000-8100" # Expose ports 8000-8100 for examples that use an HTTP server

  wadm:
    depends_on:
      - "nats"
    image: ghcr.io/wasmcloud/wadm:latest
    environment:
      - WADM_NATS_SERVER=nats
      - WASMCLOUD_OBSERVABILITY_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://otelcol:4318"
      - RUST_LOG=debug,hyper=info,async_nats=info,oci_distribution=info,cranelift_codegen=warn
 
